INSERT INTO MANUFACTURER(ID, NAME, DUNS_IDENTIFIER, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, COUNTRY, ZIP_CODE)
VALUES (1, 'ACME', '4321DCBA', '123 Coyote', 'Road runner', 'Phoenix', 'USA', '12345');
INSERT INTO MANUFACTURER(ID, NAME, DUNS_IDENTIFIER, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, COUNTRY, ZIP_CODE)
VALUES (2, 'Another ACME', '4321ABCD', '321 Coyote', 'Another road runner', 'Las Vegas', 'USA', '54321');

INSERT INTO PRODUCT (ID, PRODUCT_NAME, PRODUCT_SKU_CODE, MANUFACTURER_ID)
VALUES (1, 'Table', 'ABCD1234', 1);
INSERT INTO PRODUCT (ID, PRODUCT_NAME, PRODUCT_SKU_CODE, MANUFACTURER_ID)
VALUES (2, 'Office Chair', 'ABCE1235', 1);
INSERT INTO PRODUCT (ID, PRODUCT_NAME, PRODUCT_SKU_CODE, MANUFACTURER_ID)
VALUES (3, 'Table', 'ABCD1234', 2);
INSERT INTO PRODUCT (ID, PRODUCT_NAME, PRODUCT_SKU_CODE, MANUFACTURER_ID)
VALUES (4, 'Arm Chair', 'ABCE1236', 2);

COMMIT;
