INSERT INTO EXECUTION_CONCEPT (ID,DESCRIPTION) VALUES (1, 'CONCEPT-1');
INSERT INTO EXECUTION_CONCEPT (ID,DESCRIPTION) VALUES (2, 'CONCEPT-2');
INSERT INTO EXECUTION_CONCEPT (ID,DESCRIPTION) VALUES (3, 'CONCEPT-3');

INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (1,'LINE-01',1);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (2,'ALERT-11',1);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (3,'LINE-12',1);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (4,'CANDY-01',1);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (5,'LINE-11',1);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (6,'FIRE-12',1);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (7,'LINEAR-02',2);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (8,'ASCEND-22',2);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (9,'TRAVEL-2',2);
INSERT INTO BUSINESS_LINE (ID, DESCRIPTION, EXECUTION_ID) VALUES (10,'OFFICE-01',2);

INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (1,'AL',1);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (2,'NV',1);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (3,'GA',1);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (4,'CA',1);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (5,'TX',2);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (6,'WA',2);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (7,'FL',2);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (8,'MA',2);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (9,'NV',2);
INSERT INTO REGION (ID, DESCRIPTION, EXECUTION_ID) VALUES (10,'CO',2);

