CREATE TABLE PRODUCT (
  ID          INTEGER PRIMARY KEY,
  DESCRIPTION VARCHAR(200) NOT NULL
);

CREATE TABLE PRODUCT_LINE (
  ID           INTEGER PRIMARY KEY,
  DESCRIPTION  VARCHAR(200) NOT NULL,
  PRODUCT_ID INTEGER      NOT NULL,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE REGION (
  ID           INTEGER PRIMARY KEY,
  DESCRIPTION  VARCHAR(200) NOT NULL,
  PRODUCT_ID INTEGER      NOT NULL,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
)
