CREATE TABLE MANUFACTURER
(
    ID              INTEGER PRIMARY KEY,
    NAME            VARCHAR(200) NOT NULL,
    DUNS_IDENTIFIER VARCHAR(200) NOT NULL,
    ADDRESS_LINE_1  VARCHAR(200) NOT NULL,
    ADDRESS_LINE_2  VARCHAR(200) NOT NULL,
    CITY            VARCHAR(200) NOT NULL,
    COUNTRY         VARCHAR(200) NOT NULL,
    ZIP_CODE        VARCHAR(200) NOT NULL
);

CREATE TABLE PRODUCT
(
    ID               INTEGER PRIMARY KEY,
    PRODUCT_NAME     VARCHAR(200) NOT NULL,
    PRODUCT_SKU_CODE VARCHAR(200) NOT NULL,
    MANUFACTURER_ID  INTEGER      NOT NULL,
    FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER (ID)
);

