CREATE TABLE PRODUCT (
  ID           INTEGER PRIMARY KEY,
  NAME         VARCHAR(200) NOT NULL,
  MANUFACTURER VARCHAR(200) NOT NULL
);

CREATE TABLE SUPPLY_CHAIN (
  ID          INTEGER PRIMARY KEY,
  NAME        VARCHAR(200) NOT NULL
);

CREATE TABLE REGION (
  ID          INTEGER PRIMARY KEY,
  NAME        VARCHAR(200) NOT NULL
);

CREATE TABLE SUPPLY_CHAIN_REF (
  ID              INTEGER PRIMARY KEY,
  SUPPLY_CHAIN_ID INTEGER NOT NULL,
  PRODUCT_ID      INTEGER NOT NULL,
  FOREIGN KEY (SUPPLY_CHAIN_ID) REFERENCES SUPPLY_CHAIN (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE REGION_REF (
  ID          INTEGER PRIMARY KEY,
  REGION_ID   INTEGER NOT NULL,
  PRODUCT_ID  INTEGER      NOT NULL,
  FOREIGN KEY (REGION_ID) REFERENCES REGION (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
)
