CREATE TABLE EXECUTION_CONCEPT (
  ID          INTEGER PRIMARY KEY,
  DESCRIPTION VARCHAR(200) NOT NULL
);

CREATE TABLE BUSINESS_LINE (
  ID           INTEGER PRIMARY KEY,
  DESCRIPTION  VARCHAR(200) NOT NULL,
  EXECUTION_ID INTEGER      NOT NULL,
  FOREIGN KEY (EXECUTION_ID) REFERENCES EXECUTION_CONCEPT (ID)
);

CREATE TABLE REGION (
  ID           INTEGER PRIMARY KEY,
  DESCRIPTION  VARCHAR(200) NOT NULL,
  EXECUTION_ID INTEGER      NOT NULL,
  FOREIGN KEY (EXECUTION_ID) REFERENCES EXECUTION_CONCEPT (ID)
)
